# Copyright 2024 Google LLC
#
# This is “Software” that is licensed under the “General Software” section of
# the Service Specific Terms (https://cloud.google.com/terms/service-terms) for
# usage in accordance with the following “Scope of Use”: This file may only be
# used on an Anthos cluster, including any associated ci/cd use. “Anthos
# cluster” is defined as “A Cluster (of any kind) registered to a fleet project
# where the Anthos API is enabled”.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowPrivilegeEscalationContainer
metadata:
  name: pss-restricted-v2022-privilege-escalation
  labels:
    policycontroller.gke.io/bundleName: pss-restricted-v2022
  annotations:
    policycontroller.gke.io/bundleVersion: "202403.1"
    policycontroller.gke.io/constraintData: |-
      "{
        bundleName: 'pss-restricted-v2022',
        bundleDisplayName: 'Pod Security Standards Restricted v2022',
        bundleLink: 'https://cloud.google.com/anthos-config-management/docs/how-to/using-pss-restricted',
        bundleVersion: '202403.1',
        bundleDescription: 'Use the Pod Security Standards Restricted v2022 policy bundle with Policy Controller to achieve many of the Kubernetes Pod Security Standards Restricted policy protections.',
        controlNumbers: '[]',
        severity: 'UNSPECIFIED',
        description: 'Privilege escalation (such as via set-user-ID or set-group-ID file mode) should not be allowed.',
        remediation: 'Containers cannot run with `allowPrivilegeEscalation` set to `true`. Set your containers with `allowPrivilegeEscalation: false`.',
        minimumTemplateLibraryVersion: '1.11.1',
        constraintHash: 'd24bf9cb3555de60037a675a2198760b1eb17b452adb3be6d7b47106424cb38e'
      }"
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    excludedNamespaces:
    - kube-system
    - gke-system
    - istio-system
    - asm-system
    - config-management-system
    - config-management-monitoring
    - resource-group-system
    - cert-manager
    - anthos-identity-service
    - apigee
  parameters:
    exemptImages:
    - gcr.io/anthos-baremetal-release/*
